import mongoose from 'mongoose';

// Define the schema for storing AI-generated content
const aiOutputSchema = new mongoose.Schema({
  // The content generated by the AI model
  aiOutput: {
    type: String,       // Assuming the content is a string (e.g., text)
    required: true,     // Required field
  },
  formData: {
    type: String,       // Assuming the content is a string (e.g., text)
    required: true,     // Required field
  },

  // The ID of the user who requested the content (optional, for tracking purposes)
  // name: {
  //   type: String,
  //   ref: 'User',        // Reference to the User model (optional, for user association)
  //   required: false,    // Optional, depending on your app's needs
  // },
  // // Timestamp when the content was generated
  generatedAt: {
    type: Date,
    default: Date.now,  // Set the default to the current date and time
  },
});

// Create the model from the schema
const AIOutput = mongoose.model('AIOutput', aiOutputSchema);

export default AIOutput;